version: '3.7'

x-base: &base
    env_file:
        - .env

services:
    app:
        <<: *base
        restart: always
        build:
            context: .
            dockerfile: app/Dockerfile
        ports:
            - 127.0.0.1:${API_LOCAL_PORT}:80
        volumes:
            - ./data/resumes:/data/resumes
        
    redis:
        image: redislabs/redisearch:latest
        command: ["redis-server", "--loadmodule", "/usr/lib/redis/modules/redisearch.so", "--appendonly", "yes", "--aof-use-rdb-preamble", "yes"]
        restart: always
        ports:
            - 127.0.0.1:${REDIS_LOCAL_PORT}:6379
        volumes:
            - ./data/redis:/data